version: '2'
services:
  elasticsearch:
    ports:
        - 9200:9200
    image: elasticsearch

  kibana:
    image: kibana
    ports:
        - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200/
    labels:
      aliyun.routing.port_5601: kibana
    links:
      - elasticsearch

  pilot:
    image: pilot:latest
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/filebeat:/var/lib/filebeat
      - /var/log/filebeat:/var/log/filebeat
      - /:/host
    environment:
      PILOT_TYPE: filebeat
      PILOT_LOG_PREFIX: "aliyun,custom"
      FILEBEAT_OUTPUT: elasticsearch
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
    links:
      - elasticsearch

